-- Generated by tools/export_data.lua from the original game bytecode. Do not edit by hand.
-- Collision fixtures per map element (all use obstacleFilter, added at load time).
return {
  ["0Av1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["0Av2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["0Av3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["0Av4"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["0Bv1"] = {},
  ["0Bv2"] = {},
  ["0Bv3"] = {},
  ["0Bv4"] = {},
  ["0Bv5"] = {},
  ["0Bv6"] = {},
  ["0Cv1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["0Cv2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["0Cv3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["0Cv4"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["0Dv1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["0Dv2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["0Dv3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["0Ev1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, -21, -32, -25, 40, -25 },
    },
  },
  ["0Ev2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, -21, -32, -25, 40, -25 },
    },
  },
  ["0Ev3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, -21, -32, -25, 40, -25 },
    },
  },
  ["0Fv1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, 25, -40, -21, -32, -25, 32, -25, 40, -21, 40, 25 },
    },
  },
  ["0Fv2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, 25, -40, -21, -32, -25, 32, -25, 40, -21, 40, 25 },
    },
  },
  ["0stotte1-1"] = {},
  ["0stotte1-2"] = {},
  ["0stotte1-3"] = {},
  ["0stotte2-1"] = {},
  ["0stotte2-2"] = {},
  ["0stotte2-3"] = {},
  ["0stotte3-1"] = {},
  ["0stotte3-2"] = {},
  ["0stotte3-3"] = {},
  ["1Av1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1Av2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1Av3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1Av4"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1B"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1C1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -39, 25, 40, 12 },
    },
  },
  ["1C1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, 12, 40, 0 },
    },
  },
  ["1C1-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, 0, 40, -12 },
    },
  },
  ["1C1-4"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, -12, 40, -25 },
    },
  },
  ["1C2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1C2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1C2-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1D1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, 40, 0 },
    },
  },
  ["1D1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, 0, 40, -25 },
    },
  },
  ["1D2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1D2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1E1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, 34, 4, 40, 0 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, 29, 7, 34, 4 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, 9, 17, 29, 7 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -13, 23, 9, 17 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -30, 25, -13, 23 },
    },
  },
  ["1E1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, 25, -40, 0, -18, -13, 2, -21, 24, -25, 40, -25, 40, 25 },
    },
  },
  ["1E2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1E2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1F1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, 12, 23, 40, 20 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -25, 25, 12, 23 },
    },
  },
  ["1F1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, 19, 6, 40, 0 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -6, 13, 19, 6 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -28, 18, -40, 25, -40, 20 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -6, 13, -40, 25, -28, 18 },
    },
  },
  ["1F1-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -18, -7, 14, -15, 40, 25, -40, 25, -40, 0 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, 14, -15, 40, -20 },
    },
  },
  ["1F1-4"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 0, -24, 40, -25, 40, 25, -40, 25, -40, -20 },
    },
  },
  ["1F2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1F2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1F2-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1G1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, 17, 23, 40, 21 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -20, 25, 17, 23 },
    },
  },
  ["1G1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, 19, 8, 40, 1 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, 19, 8 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -14, 17, -40, 25, -40, 21 },
    },
  },
  ["1G1-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, 1, 40, -25 },
    },
  },
  ["1G2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1G2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1G2-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1H1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, 40, -2 },
    },
  },
  ["1H1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -18, -9, 8, -16, 27, -20, 40, -22, 40, 25, -40, 25, -40, -2 },
    },
  },
  ["1H1-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, -22, 40, -25 },
    },
  },
  ["1H2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["1H2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["2A1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -19, 25, -40, 25, 40, 0, 40, 7 },
    },
  },
  ["2A1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, 17, 25, -26, 7, -40, 0, 40, -25 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, 0, -26, 7, -40, 7 },
    },
  },
  ["2A2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, -15, -40, -15, -40, -25 },
    },
  },
  ["2A2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, -15, -40, -15, -40, -25 },
    },
  },
  ["2B"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, -15, -40, -15, -40, -25 },
    },
  },
  ["2C"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 15, 40, 25, -40, 25, -40, 15 },
    },
  },
  ["3A"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 31, 16, -33, 11, -33, 3, -24, -3, -12, -6, 31, -6 },
    },
  },
  ["3B1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 12, -36, 10, -26, 1, -13, -5, 40, -5 },
    },
  },
  ["3B2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 32, -5, 32, 12, -40, 12, -40, -5 },
    },
  },
  ["3C1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 10, -29, 10, -24, -14, 21, -14, 40, -10 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -24, -14, -29, 10, -35.151515007019, -3.88888931274414 },
    },
  },
  ["3C2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 35, 5, 35, 16, -40, 10, -40, -10 },
    },
  },
  ["3D1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -30, 25, -3, 15, 40, 10 },
    },
  },
  ["3D1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 28, 10, 35, 25, -40, 25, -40, 10 },
    },
  },
  ["3D2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -27, -5, -30, -25, 40, -25, 40, 5 },
    },
  },
  ["3D2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 10, 5, -40, 5, -40, -25, 35, -25 },
    },
  },
  ["3E1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, 8, 19, 40, 5 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -35, 25, -28, 23, 8, 19 },
    },
  },
  ["3E1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -11, -1, 28, -1, 40, 25, -40, 25, -40, 5 },
    },
  },
  ["3E2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -20, 0, -35, -25, 40, -25, 40, 10 },
    },
  },
  ["3E2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 29, 7, -40, 10 },
    },
  },
  ["3F1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -32, 25, -25, 16, 40, 5 },
    },
  },
  ["3F1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 27, 25, -40, 25, -40, 5, 27, -6 },
    },
  },
  ["3F2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 5, -15, 5, -32, -25 },
    },
  },
  ["3F2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 27, -25, -40, 0 },
    },
  },
  ["3G1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -35, 25, -24, 19, 40, 10 },
    },
  },
  ["3G1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, 10, 40, 0 },
    },
  },
  ["3G1-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 24, 5, 40, 25, -40, 25, -40, 0 },
    },
  },
  ["3G2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -20, -7, -35, -25, 40, -25, 40, 0 },
    },
  },
  ["3G2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 0, -40, 0, -40, -25 },
    },
  },
  ["3G2-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 20, 0, -40, 0, -40, -25, 40, -25 },
    },
  },
  ["3H1-1"] = {},
  ["3H1-2"] = {},
  ["3H1-3"] = {},
  ["3H2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -10, -40, -16, 40, -16, 40, 5 },
    },
  },
  ["3H2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -16, 40, 5, -40, 5, -40, -16 },
    },
  },
  ["3H2-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -16, 40, -16, 40, -10, -40, 5 },
    },
  },
  ["3I1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -30, 25, 1, 13, 40, 12 },
    },
  },
  ["3I1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, 12, 40, 9 },
    },
  },
  ["3I1-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, 10, 40, 8 },
    },
  },
  ["3I1-4"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 17.1717185974121, 13.3838376998901, 30, 25, -40, 25, -40, 8 },
    },
  },
  ["3I2-1"] = {},
  ["3I2-2"] = {},
  ["3I2-3"] = {},
  ["3I2-4"] = {},
  ["Br_0-0"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["Br_0-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["Br_1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["Br_1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["Br_2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["Br_2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["Br_3-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  Goal = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  Jump1 = {
    {
      bounce = 0,
      density = 2,
      friction = 0,
      shape = { 20, 21, 40, 25, -40, 25, -20, 21, 0, 19 },
    },
  },
  Jump2 = {},
  R0Av1 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Av2 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Av3 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Av4 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Bv1 = {},
  R0Bv2 = {},
  R0Bv3 = {},
  R0Bv4 = {},
  R0Bv5 = {},
  R0Bv6 = {},
  R0Cv1 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Cv2 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Cv3 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Cv4 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Dv1 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Dv2 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Dv3 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Ev1 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 32, -25, 40, -21, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Ev2 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 32, -25, 40, -21, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Ev3 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 32, -25, 40, -21, 40, 25, -40, 25, -40, -25 },
    },
  },
  R0Fv1 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, 25, -40, -21, -32, -25, 32, -25, 40, -21, 40, 25 },
    },
  },
  R0Fv2 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, 25, -40, -21, -32, -25, 32, -25, 40, -21, 40, 25 },
    },
  },
  ["R0stotte1-1"] = {},
  ["R0stotte1-2"] = {},
  ["R0stotte1-3"] = {},
  ["R0stotte2-1"] = {},
  ["R0stotte2-2"] = {},
  ["R0stotte2-3"] = {},
  ["R0stotte3-1"] = {},
  ["R0stotte3-2"] = {},
  ["R0stotte3-3"] = {},
  R1Av1 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  R1Av2 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  R1Av3 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  R1Av4 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  R1B = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1C1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 39, 25, -40, 25, -40, 12 },
    },
  },
  ["R1C1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 12, 40, 25, -40, 25, -40, 0 },
    },
  },
  ["R1C1-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 0, 40, 25, -40, 25, -40, -12 },
    },
  },
  ["R1C1-4"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -12, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["R1C2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1C2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1C2-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1D1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, 0 },
    },
  },
  ["R1D1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 0, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["R1D2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1D2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1E1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -9, 17, -40, 25, -40, 0 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 13, 23, -40, 25, -9, 17 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 30, 25, -40, 25, 13, 23 },
    },
  },
  ["R1E1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, -22, -25, -4, -21, 11, -16, 40, 0, 40, 25, -40, 25 },
    },
  },
  ["R1E2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1E2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1F1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 25, 25, -40, 25, -40, 20 },
    },
  },
  ["R1F1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -10, 9, -40, 25, -40, 0 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 18, 16, 40, 25, -40, 25, -10, 9 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, 18, 16, 40, 20 },
    },
  },
  ["R1F1-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -12, -15, 40, 0, 40, 25, -40, 25, -40, -20 },
    },
  },
  ["R1F1-4"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, -25, -3, -24, 40, -20 },
    },
  },
  ["R1F2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1F2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1F2-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1G1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -23, 23, -40, 25, -40, 21 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 20, 25, -40, 25, -23, 23 },
    },
  },
  ["R1G1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -18, 9, -40, 25, -40, 1 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -18, 9 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, 16, 18, 40, 21 },
    },
  },
  ["R1G1-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 1, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["R1G2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1G2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1G2-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1H1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, -2 },
    },
  },
  ["R1H1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, -22, -14, -18, 16, -10, 40, -2 },
    },
  },
  ["R1H1-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 6, -24, 40, -22, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["R1H2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R1H2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["R2A1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, 0, 40, 25, 20, 25, -40, 7 },
    },
  },
  ["R2A1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 0, 26, 7, -20, 25, -40, 25, -40, -25 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 26, 7, 40, 0, 40, 7 },
    },
  },
  ["R2A2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, -15, -40, -15, -40, -25 },
    },
  },
  ["R2A2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, -15, -40, -15, -40, -25 },
    },
  },
  R2B = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, -15, -40, -15, -40, -25 },
    },
  },
  R3A = {},
  R3B1 = {},
  R3B2 = {},
  R3C1 = {},
  R3C2 = {},
  ["R3D1-1"] = {},
  ["R3D1-2"] = {},
  ["R3D2-1"] = {},
  ["R3D2-2"] = {},
  ["R3E1-1"] = {},
  ["R3E1-2"] = {},
  ["R3E2-1"] = {},
  ["R3E2-2"] = {},
  ["R3F1-1"] = {},
  ["R3F1-2"] = {},
  ["R3F2-1"] = {},
  ["R3F2-2"] = {},
  ["R3G1-1"] = {},
  ["R3G1-2"] = {},
  ["R3G1-3"] = {},
  ["R3G2-1"] = {},
  ["R3G2-2"] = {},
  ["R3G2-3"] = {},
  ["R3H1-1"] = {},
  ["R3H1-2"] = {},
  ["R3H1-3"] = {},
  ["R3H2-1"] = {},
  ["R3H2-2"] = {},
  ["R3H2-3"] = {},
  ["R3I1-1"] = {},
  ["R3I1-2"] = {},
  ["R3I1-3"] = {},
  ["R3I1-4"] = {},
  ["R3I2-1"] = {},
  ["R3I2-2"] = {},
  ["R3I2-3"] = {},
  ["R3I2-4"] = {},
  ["RBr_0-0"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["RBr_0-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["RBr_1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["RBr_1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["RBr_2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["RBr_2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["RBr_3-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["RSlide1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 39, 25, -40, 25, -40, 12 },
    },
  },
  ["RSlide1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 12, 40, 25, -40, 25, -40, 0 },
    },
  },
  ["RSlide1-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 0, 40, 25, -40, 25, -40, -12 },
    },
  },
  ["RSlide1-4"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -12, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["RSlide2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["RSlide2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["RSlide2-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  RStup1 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, -21, -32, -25, 40, -25 },
    },
  },
  RStup2 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, -20, -32, -25, 40, -25 },
    },
  },
  RStup3 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  RStup4 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  Rbusk1 = {},
  Rbusk2 = {},
  Rbusk3 = {},
  ["RcandyStone1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -9.24066925048828, -6.66023254394531, 11.2226524353027, -6.27413177490234, 25, 5, 28, 25, -28, 25, -28, 5 },
    },
  },
  ["RcandyStone1-2"] = {},
  ["RcandyStone2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -18.8931789398193, 9.94208526611328, -11.5572719573975, 9.42728424072266, 26, 25, -29, 25, -28, 15 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = {
        17,
        -2,
        25.5083694458008,
        10.0707845687866,
        26,
        25,
        -11.5572719573975,
        9.42728424072266,
        -0.360359191894531,
        -2.67052841186523,
      },
    },
  },
  ["RcandyStone2-2"] = {},
  ["RcandyStone3-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = {
        -8.85456848144531,
        2.86357688903809,
        6.71814727783203,
        3.63577842712402,
        15.7271575927734,
        12.2586870193481,
        18,
        25,
        -22,
        25,
        -20,
        11,
      },
    },
  },
  ["RcandyStone3-2"] = {},
  ["RcandyStone4-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -15.8043766021729, 10.0707845687866, -9, 10, 10, 18, 12, 25, -24, 25, -24, 15 },
    },
  },
  ["RcandyStone4-2"] = {},
  ["Rstone1-1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 8, 0, 17, 6, 30, 21, -5, 8, 2, 0 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 30, 21, 31, 25, -30, 25, -24, 16, -5, 8 },
    },
  },
  ["Rstone1-1-2"] = {},
  ["Rstone2-1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -9, 25, -7, 21, 9, 8, 26, 15, 31, 25 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 9, 8, -7, 21, -8, 10, -6, 6 },
    },
  },
  ["Rstone2-1-2"] = {},
  ["Rstone3-1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -11, 22, -2, 22, 0, 25, -18, 25 },
    },
  },
  ["Rstone3-1-2"] = {},
  ["Rstone4-1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -35, 25, -35, 3, -19, -7, -11, -10, 0, -5, 29, 25 },
    },
  },
  ["Rstone4-1-2"] = {},
  Rstotte1 = {},
  ["Rstotte1-2"] = {},
  Rstotte2 = {},
  ["Rstotte2-2"] = {},
  Rstottev1 = {},
  Rstottev2 = {},
  Rstottev3 = {},
  Rstottev4 = {},
  Rtre1 = {},
  Rtre2 = {},
  Rtre3 = {},
  Rtre4 = {},
  ["Rtree1-1"] = {},
  ["Rtree1-2"] = {},
  ["Rtree2-1"] = {},
  ["Rtree2-2"] = {},
  Rtree3 = {},
  Rveg1 = {},
  Rveg2 = {},
  Rveg3 = {},
  Rveg4 = {},
  Rveg5 = {},
  Rveg6 = {},
  ["Slide1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -39, 25, 40, 12 },
    },
  },
  ["Slide1-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, 12, 40, 0 },
    },
  },
  ["Slide1-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, 0, 40, -12 },
    },
  },
  ["Slide1-4"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, 25, -40, 25, -40, -12, 40, -25 },
    },
  },
  ["Slide2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["Slide2-2"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  ["Slide2-3"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -40, -25, 40, -25, 40, 25, -40, 25 },
    },
  },
  Stup1 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 32, -25, 40, -22, 40, 25, -40, 25, -40, -25 },
    },
  },
  Stup2 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 30, -25, 40, -21, 40, 25, -40, 25, -40, -25 },
    },
  },
  Stup3 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  Stup4 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  busk1 = {},
  busk2 = {},
  busk3 = {},
  ["candyStone1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -3, -9, 22, -1, 29, 25, -29, 25, -29, 2 },
    },
  },
  ["candyStone1-2"] = {},
  ["candyStone2-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -12.972972869873, -2.67052841186523, 2, -2, 27, 15, 29, 25, -26, 25, -26, 8 },
    },
  },
  ["candyStone2-2"] = {},
  ["candyStone3-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -18, 25, -16, 12, -5.2509651184082, 3.1209774017334, 8, 3, 19, 11, 22, 25 },
    },
  },
  ["candyStone3-2"] = {},
  ["candyStone4-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 24, 25, -12, 25, -5.12226486206055, 15.9909906387329, 6.84684753417969, 10.7142858505249, 20, 12 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -5.12226486206055, 15.9909906387329, -12, 25, -11, 17 },
    },
  },
  ["candyStone4-2"] = {},
  gele1 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  gele2 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  gele3 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  is1 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  is2 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  is3 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  slow1 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  slow2 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  slow3 = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 40, -25, 40, 25, -40, 25, -40, -25 },
    },
  },
  ["stone1-1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 5, 9, -31, 25, -29, 20, -19, 7, -8, 0, -1, 0 },
    },
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 30, 25, -31, 25, 5, 9, 23, 15 },
    },
  },
  ["stone1-1-2"] = {},
  ["stone2-1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -31, 25, -26, 15, -9, 8, 4, 6, 8, 10, 8, 25 },
    },
  },
  ["stone2-1-2"] = {},
  ["stone3-1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { 11, 22, 18, 25, 0, 25, 2, 22 },
    },
  },
  ["stone3-1-2"] = {},
  ["stone4-1-1"] = {
    {
      bounce = 0,
      density = 2,
      friction = 0.2,
      shape = { -18, 12, -5, -1, 7, -9, 15, -9, 35, 16, 35, 25, -28, 25 },
    },
  },
  ["stone4-1-2"] = {},
  stotte1 = {},
  ["stotte1-2"] = {},
  stotte1v2 = {},
  ["stotte1v2-2"] = {},
  stotte2 = {},
  ["stotte2-2"] = {},
  stottev1 = {},
  stottev2 = {},
  stottev3 = {},
  stottev4 = {},
  tre1 = {},
  tre2 = {},
  tre3 = {},
  tre4 = {},
  ["tree1-1"] = {},
  ["tree1-2"] = {},
  ["tree2-1"] = {},
  ["tree2-2"] = {},
  tree3 = {},
  veg1 = {},
  veg2 = {},
  veg3 = {},
  veg4 = {},
  veg5 = {},
  veg6 = {},
}
