-- Generated by tools/export_data.lua from the original game bytecode. Do not edit by hand.
-- sheets[name] = Solar2D imageSheet frames (trimmed frames keep their source size).
return {
  goldfoxHeadSprite = {
    { height = 106, sourceHeight = 250, sourceWidth = 200, sourceX = 68, sourceY = 72, width = 102, x = 106, y = 2 },
    { height = 106, sourceHeight = 250, sourceWidth = 200, sourceX = 67, sourceY = 70, width = 102, x = 2, y = 110 },
    { height = 106, sourceHeight = 250, sourceWidth = 200, sourceX = 68, sourceY = 69, width = 102, x = 2, y = 2 },
    { height = 106, sourceHeight = 250, sourceWidth = 200, sourceX = 68, sourceY = 69, width = 102, x = 2, y = 2 },
    { height = 106, sourceHeight = 250, sourceWidth = 200, sourceX = 67, sourceY = 70, width = 102, x = 2, y = 110 },
    { height = 106, sourceHeight = 250, sourceWidth = 200, sourceX = 68, sourceY = 72, width = 102, x = 106, y = 2 },
    { height = 106, sourceHeight = 250, sourceWidth = 200, sourceX = 68, sourceY = 72, width = 102, x = 106, y = 2 },
  },
}
