-- Generated by tools/export_data.lua from the original game bytecode. Do not edit by hand.
-- sheets[name] = Solar2D imageSheet frames (trimmed frames keep their source size).
return {
  birdhat23Sprite = {
    { height = 164, sourceHeight = 250, sourceWidth = 250, sourceX = 47, sourceY = 14, width = 158, x = 2, y = 2 },
    { height = 164, sourceHeight = 250, sourceWidth = 250, sourceX = 47, sourceY = 14, width = 158, x = 2, y = 2 },
    { height = 164, sourceHeight = 250, sourceWidth = 250, sourceX = 47, sourceY = 13, width = 158, x = 2, y = 2 },
    { height = 164, sourceHeight = 250, sourceWidth = 250, sourceX = 47, sourceY = 12, width = 158, x = 2, y = 2 },
    { height = 164, sourceHeight = 250, sourceWidth = 250, sourceX = 47, sourceY = 13, width = 158, x = 2, y = 2 },
    { height = 164, sourceHeight = 250, sourceWidth = 250, sourceX = 47, sourceY = 14, width = 158, x = 2, y = 2 },
    { height = 164, sourceHeight = 250, sourceWidth = 250, sourceX = 47, sourceY = 14, width = 158, x = 2, y = 2 },
  },
}
